"""
Composite an official Lawn With Care brand asset onto a generated panel,
pixel-exact, instead of trusting AI to redraw it.

Per 00-Franchise/Brand/README.md ("AI Production") and the Brooks
Visual Canon Audit's "AI Logo Rule": official artwork must never be
redrawn, reconstructed, or regenerated by AI. Generate the panel with
the badge area left plain, then use this script to stamp the real
asset on top at a known position/size.

Usage:
    python3 composite_logo.py BASE.png LOGO.png -o OUT.png -x 320 -y 210 -w 90

    -x/-y: top-left corner, in pixels, where the logo should land on BASE.
    -w:    target width in pixels; height scales to preserve aspect ratio.
    Use Preview/any image viewer's pixel coordinates on BASE to find -x/-y/-w
    for a specific panel; there's no auto-detection here on purpose --
    guessing coordinates wrong is worse than a visible manual step.
"""

import argparse
from pathlib import Path

from PIL import Image


def main():
    parser = argparse.ArgumentParser(description="Composite a logo/icon onto a base image.")
    parser.add_argument("base", help="Base panel PNG (the AI-generated draft).")
    parser.add_argument("logo", help="Official logo/icon PNG to composite (with transparency).")
    parser.add_argument("-o", "--output", required=True, help="Output PNG path.")
    parser.add_argument("-x", type=int, required=True, help="Left position in pixels on the base image.")
    parser.add_argument("-y", type=int, required=True, help="Top position in pixels on the base image.")
    parser.add_argument("-w", "--width", type=int, required=True, help="Target logo width in pixels (height auto-scales).")
    args = parser.parse_args()

    base = Image.open(args.base).convert("RGBA")
    logo = Image.open(args.logo).convert("RGBA")

    scale = args.width / logo.width
    new_size = (args.width, round(logo.height * scale))
    logo = logo.resize(new_size, Image.LANCZOS)

    base.alpha_composite(logo, (args.x, args.y))

    out_path = Path(args.output)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    base.convert("RGB").save(out_path)
    print(f"Saved: {out_path} (logo placed at {args.x},{args.y}, width {args.width}px)")


if __name__ == "__main__":
    main()
